#!/usr/bin/env bash
# PR Triage Apply Script
# Generated by github-prs-triage skill
#
# Usage: bash ./apply.sh
# Prerequisites: gh auth login

set -euo pipefail

REPO="{{REPO}}"

echo "Applying triage proposals to $REPO..."
echo ""

{{#PROPOSALS}}
# PR #{{NUMBER}}: {{TITLE}}
{{#HAS_LABELS}}
gh pr edit -R "$REPO" {{NUMBER}} {{LABEL_ARGS}}
{{/HAS_LABELS}}
{{#HAS_COMMENT}}
gh pr comment -R "$REPO" {{NUMBER}} --body {{COMMENT_QUOTED}}
{{/HAS_COMMENT}}

{{/PROPOSALS}}

echo ""
echo "Done. Applied proposals to {{TOTAL_PRS}} PR(s)."
