#!/usr/bin/env bash
# Issue Triage Apply Script
# Generated by github-issues-triage skill
#
# Usage: bash ./apply.sh
# Prerequisites: gh auth login

set -euo pipefail

REPO="{{REPO}}"

echo "Applying triage proposals to $REPO..."
echo ""

{{#PROPOSALS}}
# Issue #{{NUMBER}}: {{TITLE}}
{{#HAS_LABELS}}
gh issue edit -R "$REPO" {{NUMBER}} {{LABEL_ARGS}}
{{/HAS_LABELS}}
{{#HAS_COMMENT}}
gh issue comment -R "$REPO" {{NUMBER}} --body {{COMMENT_QUOTED}}
{{/HAS_COMMENT}}

{{/PROPOSALS}}

echo ""
echo "Done. Applied proposals to {{TOTAL_ISSUES}} issue(s)."
